# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'translateMe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  platform :ios, '8.2'
  use_frameworks!

  # Pods for translateMe
  pod 'Clarifai-Apple-SDK', '3.0.0-beta5'
  pod 'Alamofire', '~> 4.6'

  target 'translateMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'translateMeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
