# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'translateMe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for translateMe
  pod 'Clarifai'

  target 'translateMeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Clarifai'
  end

  target 'translateMeUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Clarifai'
  end

end
